language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - "python setup.py develop"
    - "pip install jira_timemachine[tests] coveralls pylama pyroma"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test -v --cov jira_timemachine tests/"
    - "pylama"
    - "pyroma"
after_success:
    - coveralls

deploy:
    provider: pypi
    user: fizyk
    password:
        secure: "run travis encrypt --add deploy.password"
    on:
        tags: true
        all_branches: true
        repo: fizyk/jira_timemachine
    distributions: "sdist bdist_wheel"
