name: Test build docker

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Jira Timemechine docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
