name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@v2.4.4
    with:
      pipenv-install-options: "--skip-lock"
      mypy: true
      black: true
      ruff: true
