name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    uses: fizyk/actions-reuse/.github/workflows/shared-linters-python.yml@v3.1.1
    with:
      mypy: true
      black: true
      ruff: true
