name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@v1.1.2
    with:
      mypy: true
